/*
    GROUP BY
    조건에 맞는 사용자와 총 거래금액 조회하기

    https://school.programmers.co.kr/learn/courses/30/lessons/164668
*/

-- 코드를 입력하세요
SELECT A.WRITER_ID, B.NICKNAME, SUM(A.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD A, USED_GOODS_USER B
WHERE 
    A.WRITER_ID = B.USER_ID
AND
    A.STATUS = 'DONE'
GROUP BY A.WRITER_ID HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC